# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Registration or Card Number', max_length=30, verbose_name='Patient ID')),
                ('patient', models.CharField(help_text='Surname  Firstname  Othername', max_length=50, verbose_name='Patient Name')),
                ('date_of_visit', models.DateField(help_text='YYYY-MM-DD', verbose_name='Date of Visit')),
                ('summary_of_visit', models.TextField(blank=True, max_length=500, verbose_name='Summary of Visit')),
                ('date_of_recall', models.DateField(help_text='YYYY-MM-DD', verbose_name='Date of Recall')),
                ('reason_for_recall', models.TextField(blank=True, max_length=200, verbose_name='Reason for Recall')),
                ('recall_status', models.CharField(blank=True, choices=[('On Schedule', 'On Schedule'), ('A Reminder', 'A Reminder')], default='On Schedule', max_length=15, verbose_name='Recall Status')),
                ('phone_number', models.CharField(max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_of_recall'],
            },
        ),
    ]
